server:
  port: 8088
  tomcat:
    threads:
      max: 800

spring:
  application:
    name: juice-samples

# jackson date
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#跨域
## 允许原始域
cors:
  path: /**
  allowedOrigins: http://crm.xxx.com, https://crm.xxx.com, http://crm.xxx.test
## 允许方法
  allowedMethods: GET, POST, HEAD, PUT, DELETE
  exposedHeaders: